# -*- coding: utf-8 -*-
"""Projeto Aplicado - Análise Exploratória

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G9SFqC-8bT0lm1go9yKE9XPvASpl5g9b
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Carregar o dataset de metadados de vacinação
df = pd.read_csv('https://raw.githubusercontent.com/gelborin/projetoaplicado1_AAAEV/refs/heads/main/dataset/Global%20COVID-19%20Data%20(2020-2024)/Global%20COVID-19%20Data%20(2020-2024)/vaccination-metadata.csv', sep=';')

# Exibir as primeiras linhas do dataset
df.head()

# Dimensões do dataset (número de linhas e colunas)
df.shape

# Verificando os tipos de dados de cada coluna
df.dtypes

# Verificando valores ausentes
df.isnull().sum()

# Porcentagem de dados ausentes em cada coluna
(df.isnull().sum() / df.shape[0]) * 100

df.columns

# Remover dados duplicados nas colunas 'COMPANY_NAME' e 'VACCINE_NAME'
df_unique = df.drop_duplicates(subset=['COMPANY_NAME', 'VACCINE_NAME'])

# Contar quantas vacinas cada fabricante distribuiu
df_unique['COMPANY_NAME'].value_counts()

# Criar um gáfico de barras horizontais
df_unique['COMPANY_NAME'].value_counts().plot(kind='barh', figsize=(10,8), color='green')
plt.title('Distribuição de Vacinas por Fabricante (Valores Únicos)')
plt.xlabel('Número de vacinas')
plt.ylabel('Fabricante')
plt.show()

# Remover dados duplicados e contar vacinas por país
vacinas_por_pais = df.drop_duplicates(subset=['ISO3','VACCINE_NAME'])['ISO3'].value_counts()

# Criar uma tabela com as contagens de vacinas por país
fig, ax = plt.subplots(figsize=(10, 6))
ax.axis('tight')
ax.axis('off')
table_data = vacinas_por_pais.reset_index().values.tolist()
columns = ['País (ISO3)', 'Número de Vacinas']
ax.table(cellText=table_data, colLabels=columns, cellLoc = 'center', loc='center')
plt.title('Resumo de Vacinas por País')
plt.show()

